### ISSUE TITLE
pre-release 3.1.6 cannot run lua file

### ISSUE THREAD

**Issue by FiSHYsolutions** [PortableApps/Toucan#21]
obviously v3.1.5 is buggy because sync (mirror) doesn't delete folders recursive in its destination, so i was wondering v3.1.6 maybe is fixing this but i can't even run a sync in v3.1.6:

![toucan_3 1 6_lua_bug](https://user-images.githubusercontent.com/222112/45232178-c735d080-b2ce-11e8-8166-90854c32d98d.JPG)

**Comment by alex-ter** [comment]
No one ever reported that sync issue, so no, there were no changes to that part in 3.1.6. Feel free to create an issue for that.

The error you're showing looks like some script syntax problem, at least judging by the error message. Could you please share your script or an eqivalent reproducer, for me to be able to investigate?

**Comment by FiSHYsolutions** [comment]
there is nothing to share IMHO. i took the 3.1.6-pre-release-paf.exe, extracted and started it, and can't run a sync (neither mirror, nor copy, or something else). everytime i hit the run-button i get the error-message above. that should be pretty easy to reproduce without more input.

btw: there are no rules, variables, or scripts defined.

**Comment by alex-ter** [comment]
Ok, that looked like a custom script that was erroring out. I'll look into this.

**Comment by alex-ter** [comment]
Ok, it took me a while to get to this, but I can confirm the problem. Will investigate it and post back here when I understand what's going on. Thanks for reporting!

**Comment by alex-ter** [comment]
Okay - please try the updated release version, it fixes the problem: https://github.com/PortableApps/Toucan/releases/tag/3.1.6.1. Thanks again for reporting and apologies for having the problem in the first place - turned out to be a typo introduced during Sync logging feature update.
