### ISSUE TITLE
*** caught unhandled unknown exception; terminating

### ISSUE THREAD

**Issue by xiiviii** [PortableApps/Toucan#25]
hi,

been using toucan since 2012 however after migrating to win 10, the only functional toucan on my win 10 (1809) is version 3.1 - any build above that gives a warning msg as indicated in the title (*** caught unhandled unknown exception; terminating)

do not know what dll's missing and no toucan updates worked

Please advise or investigate
Thank you in advance!

![toucan](https://user-images.githubusercontent.com/54877051/64224035-b1d09380-ce9b-11e9-8bfb-884eec794f28.jpg)

**Comment by alex-ter** [comment]
Hmm, that's interesting (and indeed the message is quite non-informative) - I test each release on Windows 10 and Windows 7 and haven't seen anything like this and no one reported this as well. So let's see what could this be.

Several questions to understand the situation better:
1. Which version of PortableApps framework application do you have? (Portableapps app -> Help -> About)
1. Could you please post the listing of the `<your PA installation root>\PortableApps\Toucan\App\Toucan` directory, with filenames and file modification times?

In the meanwhile I'll see if by any chance my test VM doesn't have namely 1809 and that makes a difference.

**Comment by alex-ter** [comment]
One clarification - for the second part, please update the application first to the latest release, 3.1.7.

+one more thing, please check Windows Event Log, Applications section to see if there's anything more useful around the time when the app fails.

**Comment by xiiviii** [comment]
hi alex-ter,

updated win 10 to v1903 last night and problems just went away
not sure what caused it but glad the newest release 3.1.7 works

thanks for your time!

best

**Comment by alex-ter** [comment]
That's interesting and thanks for reporting back!
