### ISSUE TITLE
Blank or Empty Folders

### ISSUE THREAD

**Issue by blisstik** [PortableApps/Toucan#26]
Using the latest 3.1.7, I have an empty folder in Source that is read only, I run sync and it creates the folder on Destination. That's good.

I run it again. I expect there should be nothing to be done but now it deletes the empty read only folder in the Destination. Not good.

I need a way to sync 100%, including blank folders. Please advise.

**Comment by alex-ter** [comment]
So this is actually done explicitly, [here](https://github.com/PortableApps/Toucan/blob/master/sync/syncjob.cpp#L144-L145). I don't see any comments and the code pre-dates my involvement with Toucan.

@sjlamerton, if you're still around and willing - could you please shed some light onto that logic? Personally, I too would expect it to just sync the empty folder and leave it alone, but I guess you had your reasons?

**Comment by alex-ter** [comment]
@blisstik, just to make sure - you are using the Mirror mode, right?

**Comment by alex-ter** [comment]
Okay, so given that Steve is probably away/isn't interested any more and the logic in that piece of code doesn't make sense to me after staring at it and experimenting (also with include/excludes) for good couple of hours, I think we can simply remove it.

However I'm not fully sure there aren't any side effects - so here's the test version. I don't use Sync mode at all, so can't fully test it by myself. BTW, if that works for you - I'd recommend you to switch to [FreeFileSync](https://freefilesync.org/), works like a charm for me and is actively developed.

To make it easier to test - just temporarily replace your current Toucan binary. As there are no other changes except the differential backup bug, which shouldn't affect you, this file is fully compatible with your current rules/variables/jobs files.

However it's always wise to create a backup copy of your full Portableapps setup just in case.

Specifically:
1. Rename `<your portableapps install dir>\PortableApps\Toucan\App\Toucan\toucan.exe` to `toucan.exe.orig`
1. Unpack the attached zip and copy `toucan.exe` into the same dir
1. Run Toucan and execute your test scenarios

If that works for you, I'll put this in and make a release.

[toucan.zip](https://github.com/PortableApps/Toucan/files/3908437/toucan.zip)

SHA256 of `toucan.zip`: 902193808D4B86F9B2DDE2C9E58FD5A45E78EBFC8944D5ED85688DB4D4DF7AD1

**Comment by alex-ter** [comment]
@blisstik, is this still actual?

**Comment by alex-ter** [comment]
Closing for no response and ambiguous situation. If this is still a problem for you or anyone else reading this - please chime in and test out the program I attached earlier (make sure to backup your normal environment just in case)
