### ISSUE TITLE
Files on release page and portableapps.com are different

### ISSUE THREAD

**Issue by linsui** [PortableApps/Toucan#27]

**Comment by alex-ter** [comment]
That's expected - the release page has what I build, portableapps.com has the same, but signed by John's key. Theoretically I could add the signed version to releases as well, but as this signing is very asynchronous and I don't see much value in that anyway, I haven't done that so far (and there has been only one signed release so far I think). I'll see if this changes in the future, but given that I'm not actively developing Toucan, the chances aren't that big as the value isn't either.
