### ISSUE TITLE
Differential backup mode adds a space at end of base file name

### ISSUE THREAD

**Issue by captgeoff** [PortableApps/Toucan#28]
Updated from 3.1.5 to 3.1.7 today.  Tried to use a differential backup routine that worked in 3.1.5, but the program kept recreating the BaseFile.7z file, rather than adding a differential file.

Reinstalled 3.1.5 and ran the same routine.  I ended up with a second BaseFile.7z in the same folder, which shouldn't be possible. On further investigation there is a space after the z in the version created by 3.1.7, so I assume it is not recognized as an archive when the differential routine goes looking for it.

The differential routine does work if a BaseFile.7z exists from an earlier copy of Toucan. But if you remove that copy, the process simply creates a new BaseFile.7z each time.

![2019-11-10_18-26-42](https://user-images.githubusercontent.com/57607637/68556600-c4110580-03e7-11ea-9d4d-ff399695c573.png)

**Comment by alex-ter** [comment]
Confirmed, thanks for reporting. I don't see anything explicit there, but will investigate further. There generally weren't any changes around that piece since 3.1.5, but we'll see when the root cause is found.

**Comment by alex-ter** [comment]
Just re-checked on 3.1.5 and it actually behaves the same, there's a space after `7z` in the base file name. That confirms my previous comment regarding no changes around that piece of logic, nevertheless that's still a bug that must be fixed.

**Comment by alex-ter** [comment]
Okay, found it - looks like a typo that was there for quite a while (like "years"), the fix is on the way.
