### ISSUE TITLE
New Japanese translation is missing

### ISSUE THREAD

**Issue by maboroshin** [PortableApps/Toucan#33]
On ```Toucan_3.1.8.paf.exe```, New Japanese translation is missing. The file is dated 2016.

[The new Japanese translation](https://github.com/PortableApps/Toucan/pull/29) is labeled milestone:3.1.8.

Is there a mistake?

**Comment by alex-ter** [comment]
Hmm, indeed. Looks like a step was missing in the release procedure for updating the release package with the new lang files.

I'll correct that. @JohnTHaller, from your standpoint, is it better to release a 3.1.8(.2), or a full 3.1.9 one, if nothing else changes? IMO that's just a packaging glitch, so just bumping up that fourth version component seems to be exactly what it's there for.

**Comment by alex-ter** [comment]
All right, should be fixed now. I've updated the 3.1.8 binary (it's 3.1.8.2 vs. the original 3.1.8.1, so updates smoothly via PA) in the Releses section: https://github.com/PortableApps/Toucan/releases/tag/3.1.8.1

**Comment by maboroshin** [comment]
The update was confirmed. Thank you.👍
