### ISSUE TITLE
*** caught unhandled unknown exception; terminating

### ISSUE THREAD

**Issue by FredThompsonII** [PortableApps/Toucan#34]
I've tried running releases 3.1.7 (GitHub), 3.1.8 (GitHub), and 3.1.8.1 (PortableApp) on Win8.1x64 in C:/Portable/Toucan.

All 3 releases crash with an error window which states:

*** caught unhandled unknown exception; terminating.

How can I discover what is creating this problem?

**Comment by alex-ter** [comment]
That's an interesting one, being quite generic. You have the latest PortabelApps platform, don't you? Have you tried uninstalling Toucan, then cleaning up any remnants in the PA directory and installing again? Finally, have you checked if that's maybe an antivirus/endpoint protection on that machine preventing Toucan from running or accessing some files?

**Comment by alex-ter** [comment]
Closing for no response
