### ISSUE TITLE
Mention the new location in the sticky and in the portableapps main page

### ISSUE THREAD

**Issue by paulharris** [PortableApps/Toucan#5]
I didn't see your post in the forum, I just checked the sticky post which only mentioned github was "on the todo".

**Comment by alex-ter** [comment]
Done for the sticky thread part: http://portableapps.com/comment/223045#comment-223045
I don't have control over PortableApps page, but I've pinged @JohnTHaller asking him to do that (I could do that by myself if I had permissions).

**Comment by paulharris** [comment]
Your comment is a good start, thanks :)
