### ISSUE TITLE
macOS Ventura 13.4.1

### ISSUE THREAD

**Issue by 4pastor** [PortableApps/Toucan#52]
I am unable to install the PortableApps.com platform on my MacBook. I kept getting the error message on the attachment and I don't know what to do. Can someone please help?
<img width="654" alt="Screenshot 2023-07-20 at 10 53 30" src="https://github.com/PortableApps/Toucan/assets/96359391/f2e665dd-5b02-48f2-94c0-83cda1b9a962">
<img width="405" alt="Screenshot 2023-07-21 at 10 22 47" src="https://github.com/PortableApps/Toucan/assets/96359391/99e0b1e8-67cb-476a-9498-4395888ced7b">

**Comment by alex-ter** [comment]
This is not the right place to request assistance with PortableApps platform itself, but I see you probably (based on the username similarity) got help in the PortableApps forum I was about to point you to (https://portableapps.com/node/68834).

**Comment by 4pastor** [comment]
Sorry, I did not know, but thanks for the information.
