### ISSUE TITLE
Log file is (nearly) empty when syncing

### ISSUE THREAD

**Issue by bitkleberAST** [PortableApps/Toucan#6]
Using Toucan v3.1 (Built: Jan 13th 2013)
I have created a simple job (for testing) to mirror a directory.
When I run this in command "toucan /j LogTest /l e:\temp\LogTest.log" the file is created, but it is empty. (0 Bytes)
When I run the command "toucan /j LogTest /v /l e:\temp\LogTest.log" the fle contains the following text:
using catalog 'toucan' from 'E:\Programme Portable\PortableApps\Toucan\App\Toucan\lang\de\toucan.mo'.
Using the parameter "--log"  instead of "/l" doesn't change anything.

**Comment by alex-ter** [comment]
@bitkleberAST, try version 3.1.3, I think I have fixed this issue there - in commit 272e2b0.

Unfortunately Portableapps team has never promoted my builds to their official release channels, so you can just directly download the .paf file from the Releases section: https://github.com/PortableApps/Toucan/releases/tag/3.1.3

@JohnTHaller, maybe now, a couple of years after we initially discussed this for the first time, it would be the time to finally publish it? :smiley:

**Comment by bitkleberAST** [comment]
Yes, that's it!
Thanks :+1:

**Comment by alext-mkrs** [comment]
Glad to help :smiley:
