### ISSUE TITLE
Lua Script does not process print

### ISSUE THREAD

**Issue by MrK-git** [PortableApps/Toucan#8]
Version 3.0.4 works fine, 3.1.0 does not print out any message.
I have testet 3.1.3 too, but the bug still exists.
I cannot find the depending commit, but it has to be there somwhere.

![toucan_lua-print-error1](https://cloud.githubusercontent.com/assets/5571081/16156339/171d2422-34b4-11e6-8b9a-8b1a0676dbf6.png)
![toucan_lua-print-error2](https://cloud.githubusercontent.com/assets/5571081/16156346/1e531210-34b4-11e6-8f80-80337abd856a.png)
![toucan_lua-print-error3](https://cloud.githubusercontent.com/assets/5571081/16156349/2285c4ae-34b4-11e6-8ee3-64fb3659f4d3.png)

**Comment by alext-mkrs** [comment]
This is fixed in the commit I've just pushed, I'll make a release in a day or two.

**Comment by alex-ter** [comment]
This is fixed in the commit I've just pushed, I'll make a release in a day or two.

**Comment by alex-ter** [comment]
@MrK-git check out [release 3.1.4](https://github.com/PortableApps/Toucan/releases/tag/3.1.4), it has this fix.

@JohnTHaller, maybe it's a good time to finally promote the updated Toucan to standard PortableApps update channel?
